# servarr — the homelab Docker Compose server (github.com/andre-gonzalez/servarr,
# private), as a Proxmox VM. Replaces the Debian 13 VM it used to run on.
#
# NixOS owns the host only: users, sshd, the NFS media mount, docker, the
# checkout in /opt/servarr and its secrets. The stacks themselves stay Compose
# files in the servarr repo, deployed by its own CI (ci/deploy.sh) and bumped
# by Renovate — nothing about a container is declared here.
#
# Built from nixpkgs-stable (flake.nix), unlike the laptops: this machine is
# the LAN's DNS server and should move slower than they do.
#
# Install and cutover from Debian: INSTALL.md next to this file.
{ lib, pkgs, ... }:
{
  imports = [
    # Regenerated by nixos-anywhere --generate-hardware-config on install day;
    # the tracked file is a generic QEMU guest placeholder so the flake
    # evaluates before that.
    ./hardware-configuration.nix

    ../../modules/nixos/base
    ../../modules/nixos/hardware/disko-ext4.nix
    ../../modules/nixos/services/tailscale.nix
    ../../modules/nixos/services/docker.nix

    ./ssh-totp.nix
    ./deploy.nix
    ./storage.nix
    ./dns.nix
    ./radicale-push.nix
  ];

  networking.hostName = "servarr";

  # The stacks run as PUID/PGID 1000 (the servarr repo's .env), and every file
  # in /srv/servarr copied from Debian belongs to 1000:1000. base/users.nix
  # pins the gid; pin the uid too instead of trusting allocation order.
  users.users.frank.uid = 1000;

  # Proxmox VM: virtio disk, QEMU guest agent for clean shutdowns and IP
  # reporting in the Proxmox UI.
  disko.devices.disk.main.device = "/dev/sda";
  services.qemuGuest.enable = true;

  # OVMF (UEFI) VM. Installed to the removable-media path as well, so the VM
  # still boots if its EFI vars disk is ever recreated.
  boot.loader.systemd-boot = {
    enable = true;
    configurationLimit = 20;
  };
  boot.loader.efi.canTouchEfiVariables = false;
  boot.loader.timeout = 2;

  # Intel UHD 630 (Coffee Lake, 8086:3e98) passed through from the Proxmox
  # host for Jellyfin's QuickSync (/dev/dri in stacks/media). The in-kernel
  # i915 driver binds it; the GuC/HuC firmware it loads comes from here. The
  # VA-API userspace lives in the Jellyfin image, not on the host.
  hardware.enableRedistributableFirmware = true;

  # Docker: as on Debian, nothing prunes behind the deploy's back. The weekly
  # `docker system prune` from services/docker.nix would also delete stopped
  # containers and the networks of a stopped stack.
  virtualisation.docker.autoPrune.enable = lib.mkForce false;
  # live-restore is already on by default in nixpkgs: a nixos-rebuild that
  # restarts dockerd (a docker version bump) leaves the containers running.

  # Home Assistant runs with network_mode: host, so its port is not a
  # Docker-published one (those bypass the input chain via DNAT) and the
  # NixOS firewall filters it. LAN only, like SSH.
  networking.firewall.extraInputRules = ''
    ip saddr 192.168.0.0/16 tcp dport 8123 accept
  '';

  environment.systemPackages = with pkgs; [
    git
    rsync
  ];

  system.stateVersion = "26.05";
}
